import urllib.parse
import csv
import requests

# Some helper mappings (small set here, full one can be extended)
country_data = [
    {
        "name": "Afghanistan",
        "region": "Asia",
        "memberships": ["UN"],
        "special_tags": ["landlocked"],
        "emoji": "🇦🇫",
    },
    {
        "name": "Albania",
        "region": "Europe",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇦🇱",
    },
    {
        "name": "Algeria",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇩🇿",
    },
    {
        "name": "Andorra",
        "region": "Europe",
        "memberships": ["UN"],
        "special_tags": ["microstate"],
        "emoji": "🇦🇩",
    },
    {
        "name": "Angola",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇦🇴",
    },
    {
        "name": "Antigua and Barbuda",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": ["island nation"],
        "emoji": "🇦🇬",
    },
    {
        "name": "Argentina",
        "region": "South America",
        "memberships": ["UN", "G20"],
        "special_tags": [],
        "emoji": "🇦🇷",
    },
    {
        "name": "Armenia",
        "region": "Asia",
        "memberships": ["UN"],
        "special_tags": ["landlocked"],
        "emoji": "🇦🇲",
    },
    {
        "name": "Aruba",
        "region": "North America",
        "memberships": [],
        "special_tags": ["special status", "Netherlands"],
        "emoji": "🇦🇼",
    },
    {
        "name": "Australia",
        "region": "Oceania",
        "memberships": ["UN", "G20"],
        "special_tags": [],
        "emoji": "🇦🇺",
    },
    {
        "name": "Austria",
        "region": "Europe",
        "memberships": ["UN", "EU"],
        "special_tags": [],
        "emoji": "🇦🇹",
    },
    {
        "name": "Azerbaijan",
        "region": "Asia",
        "memberships": ["UN", "CIS"],
        "special_tags": [],
        "emoji": "🇦🇿",
    },
    {
        "name": "Bahamas",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇧🇸",
    },
    {
        "name": "Bahrain",
        "region": "Asia",
        "memberships": ["UN", "GCC"],
        "special_tags": [],
        "emoji": "🇧🇭",
    },
    {
        "name": "Bangladesh",
        "region": "Asia",
        "memberships": ["UN", "SAARC"],
        "special_tags": [],
        "emoji": "🇧🇩",
    },
    {
        "name": "Barbados",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇧🇧",
    },
    {
        "name": "Belarus",
        "region": "Europe",
        "memberships": ["UN", "CIS"],
        "special_tags": ["partially recognized"],
        "emoji": "🇧🇾",
    },
    {
        "name": "Belgium",
        "region": "Europe",
        "memberships": ["UN", "EU", "NATO"],
        "special_tags": [],
        "emoji": "🇧🇪",
    },
    {
        "name": "Belize",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇧🇿",
    },
    {
        "name": "Benin",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇧🇯",
    },
    {
        "name": "Bhutan",
        "region": "Asia",
        "memberships": ["UN"],
        "special_tags": ["landlocked"],
        "emoji": "🇧🇹",
    },
    {
        "name": "Bolivia",
        "region": "South America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇧🇴",
    },
    {
        "name": "Bosnia and Herzegovina",
        "region": "Europe",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇧🇦",
    },
    {
        "name": "Botswana",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇧🇼",
    },
    {
        "name": "Brazil",
        "region": "South America",
        "memberships": ["UN", "G20", "BRICS"],
        "special_tags": [],
        "emoji": "🇧🇷",
    },
    {
        "name": "Brunei",
        "region": "Asia",
        "memberships": ["UN"],
        "special_tags": ["microstate"],
        "emoji": "🇧🇳",
    },
    {
        "name": "Bulgaria",
        "region": "Europe",
        "memberships": ["UN", "EU", "NATO"],
        "special_tags": [],
        "emoji": "🇧🇬",
    },
    {
        "name": "Burkina Faso",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇧🇫",
    },
    {
        "name": "Burundi",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇧🇮",
    },
    {
        "name": "Cabo Verde",
        "region": "Africa",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇨🇻",
    },
    {
        "name": "Cambodia",
        "region": "Asia",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇰🇭",
    },
    {
        "name": "Cameroon",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇨🇲",
    },
    {
        "name": "Canada",
        "region": "North America",
        "memberships": ["UN", "G7", "NATO"],
        "special_tags": [],
        "emoji": "🇨🇦",
    },
    {
        "name": "Central African Republic",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇨🇫",
    },
    {
        "name": "Chad",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇹🇩",
    },
    {
        "name": "Chile",
        "region": "South America",
        "memberships": ["UN", "PACI", "G20"],
        "special_tags": [],
        "emoji": "🇨🇱",
    },
    {
        "name": "China",
        "region": "Asia",
        "memberships": ["UN", "BRICS"],
        "special_tags": [],
        "emoji": "🇨🇳",
    },
    {
        "name": "Colombia",
        "region": "South America",
        "memberships": ["UN", "G20"],
        "special_tags": [],
        "emoji": "🇨🇴",
    },
    {
        "name": "Comoros",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇰🇲",
    },
    {
        "name": "Congo",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇨🇬",
    },
    {
        "name": "Congo (Democratic Republic)",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇨🇩",
    },
    {
        "name": "Costa Rica",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇨🇷",
    },
    {
        "name": "Croatia",
        "region": "Europe",
        "memberships": ["UN", "EU", "NATO"],
        "special_tags": [],
        "emoji": "🇭🇷",
    },
    {
        "name": "Cuba",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇨🇺",
    },
    {
        "name": "Cyprus",
        "region": "Asia",
        "memberships": ["UN"],
        "special_tags": ["special status"],
        "emoji": "🇨🇾",
    },
    {
        "name": "Czech Republic",
        "region": "Europe",
        "memberships": ["UN", "EU", "NATO"],
        "special_tags": [],
        "emoji": "🇨🇿",
    },
    {
        "name": "Denmark",
        "region": "Europe",
        "memberships": ["UN", "EU", "NATO"],
        "special_tags": [],
        "emoji": "🇩🇰",
    },
    {
        "name": "Djibouti",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇩🇯",
    },
    {
        "name": "Dominica",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇩🇲",
    },
    {
        "name": "Dominican Republic",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇩🇴",
    },
    {
        "name": "East Timor",
        "region": "Asia",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇹🇱",
    },
    {
        "name": "Ecuador",
        "region": "South America",
        "memberships": ["UN", "PACI"],
        "special_tags": [],
        "emoji": "🇪🇨",
    },
    {
        "name": "Egypt",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇪🇬",
    },
    {
        "name": "El Salvador",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇸🇻",
    },
    {
        "name": "Equatorial Guinea",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇬🇶",
    },
    {
        "name": "Eritrea",
        "region": "Africa",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇪🇷",
    },
    {
        "name": "Estonia",
        "region": "Europe",
        "memberships": ["UN", "EU"],
        "special_tags": [],
        "emoji": "🇪🇪",
    },
    {
        "name": "Eswatini",
        "region": "Africa",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇸🇿",
    },
    {
        "name": "Ethiopia",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇪🇹",
    },
    {
        "name": "Fiji",
        "region": "Oceania",
        "memberships": ["UN", "PIF"],
        "special_tags": [],
        "emoji": "🇫🇯",
    },
    {
        "name": "Finland",
        "region": "Europe",
        "memberships": ["UN", "EU", "NATO"],
        "special_tags": [],
        "emoji": "🇫🇮",
    },
    {
        "name": "France",
        "region": "Europe",
        "memberships": ["UN", "EU", "NATO"],
        "special_tags": [],
        "emoji": "🇫🇷",
    },
    {
        "name": "Gabon",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇬🇦",
    },
    {
        "name": "Gambia",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇬🇲",
    },
    {
        "name": "Georgia",
        "region": "Asia",
        "memberships": ["UN", "CIS"],
        "special_tags": ["partially recognized"],
        "emoji": "🇬🇪",
    },
    {
        "name": "Germany",
        "region": "Europe",
        "memberships": ["UN", "EU", "G7"],
        "special_tags": [],
        "emoji": "🇩🇪",
    },
    {
        "name": "Ghana",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇬🇭",
    },
    {
        "name": "Greece",
        "region": "Europe",
        "memberships": ["UN", "EU", "NATO"],
        "special_tags": [],
        "emoji": "🇬🇷",
    },
    {
        "name": "Grenada",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇬🇩",
    },
    {
        "name": "Guatemala",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇬🇹",
    },
    {
        "name": "Guinea",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇬🇳",
    },
    {
        "name": "Guinea-Bissau",
        "region": "Africa",
        "memberships": ["UN", "AU"],
        "special_tags": [],
        "emoji": "🇬🇼",
    },
    {
        "name": "Guyana",
        "region": "South America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇬🇾",
    },
    {
        "name": "Haiti",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇭🇹",
    },
    {
        "name": "Honduras",
        "region": "North America",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇭🇳",
    },
    {
        "name": "Hungary",
        "region": "Europe",
        "memberships": ["UN", "EU", "NATO"],
        "special_tags": [],
        "emoji": "🇭🇺",
    },
    {
        "name": "Iceland",
        "region": "Europe",
        "memberships": ["UN"],
        "special_tags": ["island"],
        "emoji": "🇮🇸",
    },
    {
        "name": "India",
        "region": "Asia",
        "memberships": ["UN", "BRICS", "SAARC"],
        "special_tags": [],
        "emoji": "🇮🇳",
    },
    {
        "name": "Indonesia",
        "region": "Asia",
        "memberships": ["UN", "ASEAN"],
        "special_tags": [],
        "emoji": "🇮🇩",
    },
    {
        "name": "Iran",
        "region": "Asia",
        "memberships": ["UN"],
        "special_tags": [],
        "emoji": "🇮🇷",
    },
    {
        "name": "Iraq",
        "region": "Asia",
        "memberships": ["UN", "OIC"],
        "special_tags": [],
        "emoji": "🇮🇶",
    },
    {
        "name": "Ireland",
        "region": "Europe",
        "memberships": ["UN", "EU"],
        "special_tags": [],
        "emoji": "🇮🇪",
    },
    {
        "name": "Israel",
        "region": "Asia",
        "memberships": ["UN"],
        "special_tags": ["partially recognized"],
        "emoji": "🇮🇱",
    },
    {
        "name": "Italy",
        "region": "Europe",
        "memberships": ["UN", "EU", "G7"],
        "special_tags": [],
        "emoji": "🇮🇹",
    },
]

country_data.extend(
    [
        {
            "name": "Haiti",
            "region": "North America",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇭🇹",
        },
        {
            "name": "Honduras",
            "region": "North America",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇭🇳",
        },
        {
            "name": "Hungary",
            "region": "Europe",
            "memberships": ["UN", "EU", "NATO"],
            "special_tags": [],
            "emoji": "🇭🇺",
        },
        {
            "name": "Iceland",
            "region": "Europe",
            "memberships": ["UN"],
            "special_tags": ["island"],
            "emoji": "🇮🇸",
        },
        {
            "name": "India",
            "region": "Asia",
            "memberships": ["UN", "BRICS", "SAARC"],
            "special_tags": [],
            "emoji": "🇮🇳",
        },
        {
            "name": "Indonesia",
            "region": "Asia",
            "memberships": ["UN", "ASEAN"],
            "special_tags": [],
            "emoji": "🇮🇩",
        },
        {
            "name": "Iran",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇮🇷",
        },
        {
            "name": "Iraq",
            "region": "Asia",
            "memberships": ["UN", "OIC"],
            "special_tags": [],
            "emoji": "🇮🇶",
        },
        {
            "name": "Ireland",
            "region": "Europe",
            "memberships": ["UN", "EU"],
            "special_tags": [],
            "emoji": "🇮🇪",
        },
        {
            "name": "Israel",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": ["partially recognized"],
            "emoji": "🇮🇱",
        },
        {
            "name": "Italy",
            "region": "Europe",
            "memberships": ["UN", "EU", "G7"],
            "special_tags": [],
            "emoji": "🇮🇹",
        },
        {
            "name": "Jamaica",
            "region": "North America",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇯🇲",
        },
        {
            "name": "Japan",
            "region": "Asia",
            "memberships": ["UN", "G7"],
            "special_tags": [],
            "emoji": "🇯🇵",
        },
        {
            "name": "Jordan",
            "region": "Asia",
            "memberships": ["UN", "OIC"],
            "special_tags": [],
            "emoji": "🇯🇴",
        },
        {
            "name": "Kazakhstan",
            "region": "Asia",
            "memberships": ["UN", "CIS"],
            "special_tags": [],
            "emoji": "🇰🇿",
        },
        {
            "name": "Kenya",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇰🇪",
        },
        {
            "name": "Kiribati",
            "region": "Oceania",
            "memberships": ["UN"],
            "special_tags": ["island nation"],
            "emoji": "🇰🇮",
        },
        {
            "name": "Korea (North)",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇰🇵",
        },
        {
            "name": "Korea (South)",
            "region": "Asia",
            "memberships": ["UN", "G20"],
            "special_tags": [],
            "emoji": "🇰🇷",
        },
        {
            "name": "Kuwait",
            "region": "Asia",
            "memberships": ["UN", "GCC"],
            "special_tags": [],
            "emoji": "🇰🇼",
        },
        {
            "name": "Kyrgyzstan",
            "region": "Asia",
            "memberships": ["UN", "CIS"],
            "special_tags": [],
            "emoji": "🇰🇬",
        },
        {
            "name": "Laos",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇱🇦",
        },
        {
            "name": "Latvia",
            "region": "Europe",
            "memberships": ["UN", "EU"],
            "special_tags": [],
            "emoji": "🇱🇻",
        },
        {
            "name": "Lebanon",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇱🇧",
        },
        {
            "name": "Lesotho",
            "region": "Africa",
            "memberships": ["UN"],
            "special_tags": ["landlocked"],
            "emoji": "🇱🇸",
        },
        {
            "name": "Liberia",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇱🇸",
        },
        {
            "name": "Libya",
            "region": "Africa",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇱🇾",
        },
        {
            "name": "Liechtenstein",
            "region": "Europe",
            "memberships": ["UN"],
            "special_tags": ["microstate"],
            "emoji": "🇱🇮",
        },
        {
            "name": "Lithuania",
            "region": "Europe",
            "memberships": ["UN", "EU"],
            "special_tags": [],
            "emoji": "🇱🇹",
        },
        {
            "name": "Luxembourg",
            "region": "Europe",
            "memberships": ["UN", "EU"],
            "special_tags": ["microstate"],
            "emoji": "🇱🇺",
        },
        {
            "name": "Madagascar",
            "region": "Africa",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇲🇬",
        },
        {
            "name": "Malawi",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇲🇼",
        },
        {
            "name": "Malaysia",
            "region": "Asia",
            "memberships": ["UN", "ASEAN"],
            "special_tags": [],
            "emoji": "🇲🇾",
        },
        {
            "name": "Maldives",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": ["island nation"],
            "emoji": "🇲🇻",
        },
        {
            "name": "Mali",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇲🇱",
        },
        {
            "name": "Malta",
            "region": "Europe",
            "memberships": ["UN", "EU"],
            "special_tags": [],
            "emoji": "🇲🇹",
        },
        {
            "name": "Marshall Islands",
            "region": "Oceania",
            "memberships": ["UN"],
            "special_tags": ["micronation"],
            "emoji": "🇲🇭",
        },
        {
            "name": "Mauritania",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇲🇷",
        },
        {
            "name": "Mauritius",
            "region": "Africa",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇲🇺",
        },
        {
            "name": "Mexico",
            "region": "North America",
            "memberships": ["UN", "G20"],
            "special_tags": [],
            "emoji": "🇲🇽",
        },
        {
            "name": "Micronesia",
            "region": "Oceania",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇫🇲",
        },
        {
            "name": "Moldova",
            "region": "Europe",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇲🇩",
        },
        {
            "name": "Monaco",
            "region": "Europe",
            "memberships": ["UN"],
            "special_tags": ["microstate"],
            "emoji": "🇲🇨",
        },
        {
            "name": "Mongolia",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇲🇳",
        },
        {
            "name": "Montenegro",
            "region": "Europe",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇲🇪",
        },
        {
            "name": "Morocco",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇲🇦",
        },
        {
            "name": "Mozambique",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇲🇿",
        },
        {
            "name": "Myanmar",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇲🇲",
        },
    ]
)

country_data.extend(
    [
        {
            "name": "Namibia",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇳🇦",
        },
        {
            "name": "Nauru",
            "region": "Oceania",
            "memberships": ["UN"],
            "special_tags": ["island nation", "microstate"],
            "emoji": "🇳🇷",
        },
        {
            "name": "Nepal",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇳🇵",
        },
        {
            "name": "Netherlands",
            "region": "Europe",
            "memberships": ["UN", "EU", "NATO"],
            "special_tags": [],
            "emoji": "🇳🇱",
        },
        {
            "name": "New Zealand",
            "region": "Oceania",
            "memberships": ["UN", "CWE"],
            "special_tags": [],
            "emoji": "🇳🇿",
        },
        {
            "name": "Nicaragua",
            "region": "North America",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇳🇮",
        },
        {
            "name": "Niger",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇳🇪",
        },
        {
            "name": "Nigeria",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇳🇬",
        },
        {
            "name": "North Macedonia",
            "region": "Europe",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇲🇰",
        },
        {
            "name": "Norway",
            "region": "Europe",
            "memberships": ["UN", "EU", "NATO"],
            "special_tags": [],
            "emoji": "🇳🇴",
        },
        {
            "name": "Oman",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇴🇲",
        },
        {
            "name": "Pakistan",
            "region": "Asia",
            "memberships": ["UN", "SAARC"],
            "special_tags": [],
            "emoji": "🇵🇰",
        },
        {
            "name": "Palau",
            "region": "Oceania",
            "memberships": ["UN"],
            "special_tags": ["micronation"],
            "emoji": "🇵🇼",
        },
        {
            "name": "Panama",
            "region": "North America",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇵🇦",
        },
        {
            "name": "Papua New Guinea",
            "region": "Oceania",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇵🇬",
        },
        {
            "name": "Paraguay",
            "region": "South America",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇵🇾",
        },
        {
            "name": "Peru",
            "region": "South America",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇵🇪",
        },
        {
            "name": "Philippines",
            "region": "Asia",
            "memberships": ["UN", "ASEAN"],
            "special_tags": [],
            "emoji": "🇵🇭",
        },
        {
            "name": "Poland",
            "region": "Europe",
            "memberships": ["UN", "EU", "NATO"],
            "special_tags": [],
            "emoji": "🇵🇱",
        },
        {
            "name": "Portugal",
            "region": "Europe",
            "memberships": ["UN", "EU", "NATO"],
            "special_tags": [],
            "emoji": "🇵🇹",
        },
        {
            "name": "Qatar",
            "region": "Asia",
            "memberships": ["UN", "GCC"],
            "special_tags": [],
            "emoji": "🇶🇦",
        },
        {
            "name": "Romania",
            "region": "Europe",
            "memberships": ["UN", "EU", "NATO"],
            "special_tags": [],
            "emoji": "🇷🇴",
        },
        {
            "name": "Russia",
            "region": "Asia",
            "memberships": ["UN", "CIS", "G20"],
            "special_tags": [],
            "emoji": "🇷🇺",
        },
        {
            "name": "Rwanda",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇷🇼",
        },
        {
            "name": "Saint Kitts and Nevis",
            "region": "Caribbean",
            "memberships": ["UN"],
            "special_tags": ["island nation"],
            "emoji": "🇰🇳",
        },
        {
            "name": "Saint Lucia",
            "region": "Caribbean",
            "memberships": ["UN"],
            "special_tags": ["island nation"],
            "emoji": "🇱🇨",
        },
        {
            "name": "Saint Vincent and the Grenadines",
            "region": "Caribbean",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇻🇨",
        },
        {
            "name": "Samoa",
            "region": "Oceania",
            "memberships": ["UN"],
            "special_tags": ["island nation"],
            "emoji": "🇼🇸",
        },
        {
            "name": "San Marino",
            "region": "Europe",
            "memberships": ["UN"],
            "special_tags": ["microstate"],
            "emoji": "🇸🇲",
        },
        {
            "name": "Sao Tome and Principe",
            "region": "Africa",
            "memberships": ["UN"],
            "special_tags": ["island nation"],
            "emoji": "🇸🇹",
        },
        {
            "name": "Saudi Arabia",
            "region": "Asia",
            "memberships": ["UN", "OIC"],
            "special_tags": [],
            "emoji": "🇸🇦",
        },
        {
            "name": "Senegal",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇸🇳",
        },
        {
            "name": "Serbia",
            "region": "Europe",
            "memberships": ["UN"],
            "special_tags": ["partially recognized"],
            "emoji": "🇷🇸",
        },
        {
            "name": "Seychelles",
            "region": "Africa",
            "memberships": ["UN"],
            "special_tags": ["island nation"],
            "emoji": "🇸🇨",
        },
        {
            "name": "Sierra Leone",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇸🇱",
        },
        {
            "name": "Singapore",
            "region": "Asia",
            "memberships": ["UN", "ASEAN"],
            "special_tags": [],
            "emoji": "🇸🇬",
        },
        {
            "name": "Slovakia",
            "region": "Europe",
            "memberships": ["UN", "EU", "NATO"],
            "special_tags": [],
            "emoji": "🇸🇰",
        },
        {
            "name": "Slovenia",
            "region": "Europe",
            "memberships": ["UN", "EU"],
            "special_tags": [],
            "emoji": "🇸🇮",
        },
        {
            "name": "Solomon Islands",
            "region": "Oceania",
            "memberships": ["UN"],
            "special_tags": ["island nation"],
            "emoji": "🇸🇧",
        },
        {
            "name": "Somalia",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇸🇴",
        },
        {
            "name": "South Africa",
            "region": "Africa",
            "memberships": ["UN", "AU", "BRICS"],
            "special_tags": [],
            "emoji": "🇿🇦",
        },
        {
            "name": "South Korea",
            "region": "Asia",
            "memberships": ["UN", "G20"],
            "special_tags": [],
            "emoji": "🇰🇷",
        },
        {
            "name": "South Sudan",
            "region": "Africa",
            "memberships": ["UN"],
            "special_tags": ["partially recognized"],
            "emoji": "🇸🇸",
        },
    ]
)

country_data.extend(
    [
        {
            "name": "Taiwan",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": ["partially recognized", "special status"],
            "emoji": "🇹🇼",
        },
        {
            "name": "Tajikistan",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇹🇯",
        },
        {
            "name": "Tanzania",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇹🇿",
        },
        {
            "name": "Thailand",
            "region": "Asia",
            "memberships": ["UN", "ASEAN"],
            "special_tags": [],
            "emoji": "🇹🇭",
        },
        {
            "name": "Togo",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇹🇬",
        },
        {
            "name": "Tonga",
            "region": "Oceania",
            "memberships": ["UN"],
            "special_tags": ["island nation"],
            "emoji": "🇹🇴",
        },
        {
            "name": "Trinidad and Tobago",
            "region": "Caribbean",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇹🇹",
        },
        {
            "name": "Tunisia",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇹🇳",
        },
        {
            "name": "Turkey",
            "region": "Asia",
            "memberships": ["UN", "NATO", "G20"],
            "special_tags": [],
            "emoji": "🇹🇷",
        },
        {
            "name": "Turkmenistan",
            "region": "Asia",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇹🇲",
        },
        {
            "name": "Tuvalu",
            "region": "Oceania",
            "memberships": ["UN"],
            "special_tags": ["island nation", "microstate"],
            "emoji": "🇹🇻",
        },
        {
            "name": "Uganda",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇺🇬",
        },
        {
            "name": "Ukraine",
            "region": "Europe",
            "memberships": ["UN", "G20"],
            "special_tags": [],
            "emoji": "🇺🇦",
        },
        {
            "name": "United Arab Emirates",
            "region": "Asia",
            "memberships": ["UN", "GCC"],
            "special_tags": [],
            "emoji": "🇦🇪",
        },
        {
            "name": "United Kingdom",
            "region": "Europe",
            "memberships": ["UN", "G7", "NATO"],
            "special_tags": [],
            "emoji": "🇬🇧",
        },
        {
            "name": "United States",
            "region": "North America",
            "memberships": ["UN", "NATO", "G7"],
            "special_tags": [],
            "emoji": "🇺🇸",
        },
        {
            "name": "Uruguay",
            "region": "South America",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇺🇾",
        },
        {
            "name": "Uzbekistan",
            "region": "Asia",
            "memberships": ["UN", "CIS"],
            "special_tags": [],
            "emoji": "🇺🇿",
        },
        {
            "name": "Vanuatu",
            "region": "Oceania",
            "memberships": ["UN"],
            "special_tags": ["island nation"],
            "emoji": "🇻🇺",
        },
        {
            "name": "Vatican City",
            "region": "Europe",
            "memberships": ["UN"],
            "special_tags": ["microstate", "theocratic"],
            "emoji": "🇻🇦",
        },
        {
            "name": "Venezuela",
            "region": "South America",
            "memberships": ["UN"],
            "special_tags": [],
            "emoji": "🇻🇪",
        },
        {
            "name": "Vietnam",
            "region": "Asia",
            "memberships": ["UN", "ASEAN"],
            "special_tags": [],
            "emoji": "🇻🇳",
        },
        {
            "name": "Yemen",
            "region": "Asia",
            "memberships": ["UN", "OIC"],
            "special_tags": [],
            "emoji": "🇾🇪",
        },
        {
            "name": "Zambia",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇿🇲",
        },
        {
            "name": "Zimbabwe",
            "region": "Africa",
            "memberships": ["UN", "AU"],
            "special_tags": [],
            "emoji": "🇿🇼",
        },
    ]
)


def get_flag_url(country_name):
    """Generate a Wikipedia flag PNG link for a country."""
    base_url = "https://en.wikipedia.org/wiki/"
    page_title = f"Flag_of_{country_name.replace(' ', '_')}"
    url = base_url + urllib.parse.quote(page_title)

    try:
        response = requests.get(url)
        if response.status_code == 200:
            # Look for the first PNG link in the HTML
            start = response.text.find("upload.wikimedia.org")
            if start != -1:
                end = response.text.find(".png", start)
                if end != -1:
                    return "https://" + response.text[start : end + 4]
    except Exception as e:
        print(f"Failed to fetch flag for {country_name}: {e}")
    return ""


def estimate_difficulty(name, special_tags):
    """Rough difficulty estimate based on size/status."""
    if "microstate" in special_tags:
        return 4.0
    if "partially recognized" in special_tags or "unrecognized" in special_tags:
        return 3.5
    if "special status" in special_tags:
        return 2.5
    return 1.0


# Write CSV
with open("flags_full.csv", mode="w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow(["name", "description", "difficulty", "image", "emoji"])

    for entry in country_data:
        name = entry["name"]
        tags = [entry["region"]] + entry["memberships"] + entry["special_tags"]
        description = ", ".join(tags)
        difficulty = estimate_difficulty(name, entry["special_tags"])
        image = get_flag_url(name)
        emoji = entry["emoji"]

        writer.writerow([name, description, difficulty, image, emoji])

print("✅ flags_full.csv generated successfully!")
